### ISSUE TITLE
Chrome

### ISSUE THREAD

**Issue by Aleksandrt6** [columndeeply/hosts#8] opened 2024-07-28 23:58 UTC
https://www.google.com/search?q=porn&oq=&gs_lcrp=EgZjaHJvbWUqCQgAEEUYOxjCAzIJCAAQRRg7GMIDMgkIARBFGDsYwgMyCQgCEEUYOxjCAzIJCAMQRRg7GMIDMgkIBBBFGDsYwgMyCQgFEEUYOxjCAzIJCAYQRRg7GMIDMhEIBxAAGAMYQhiPARi0AhjqAjIRCAgQABgDGEIYjwEYtAIY6gIyEQgJEAAYAxhCGI8BGLQCGOoCMhEIChAAGAMYQhiPARi0AhjqAjIRCAsQABgDGEIYjwEYtAIY6gLSAQYtMWowajeoAgywAgE&client=ms-android-tmus-us-rvc3&sourceid=chrome-mobile&ie=UTF-8#vhid=zephyr:0&vssid=atritem-https://www.pornhub.com/
![Screenshot_20240728_194304_One UI Home](https://github.com/user-attachments/assets/4a6d1c15-a97b-4b48-997c-aab03115482f)

**Comment by columndeeply** [comment] 2024-07-31 18:14
What am I supposed to be looking at here? Please explain what your problem is instead of just a screenshot and a google images link...

**Comment by Aleksandrt6** [comment] 2024-07-31 18:17
Block porn site ,google playstore app internet.  I don't why is not remove it ,just remove porn safsearch filter isn't work well ,kindly fix safsearch Block site unrated, block site website explicitly strong content could remove please

**Comment by columndeeply** [comment] 2024-08-01 18:25
Sorry but I can't reproduce this issue on my machines. Google safe search works fine for me.

Keep in mind that manually disabling safe search once overrides the setting until its enabled manually again. Try searching on a private tab and see if the safe search is still disabled

**Comment by Aleksandrt6** [comment] 2024-08-01 18:28
It will not show any more porn

**Comment by columndeeply** [comment] 2024-08-14 14:28
Then the issue is in your browser. Enable Safe Search manually and it should override whatever settings you had set. Closing this as it's not an issue with the list itself.

**Closed by columndeeply** 2024-08-14 14:28 UTC
